// flow-typed signature: 397328e4b1885649e61a46c3dc5e6a06
// flow-typed version: <<STUB>>/rc-form_v^2.2.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-form/dist/rc-form' {
  declare module.exports: any;
}

declare module 'rc-form/dist/rc-form.min' {
  declare module.exports: any;
}

declare module 'rc-form/es/createBaseForm' {
  declare module.exports: any;
}

declare module 'rc-form/es/createDOMForm' {
  declare module.exports: any;
}

declare module 'rc-form/es/createFieldsStore' {
  declare module.exports: any;
}

declare module 'rc-form/es/createForm' {
  declare module.exports: any;
}

declare module 'rc-form/es/createFormField' {
  declare module.exports: any;
}

declare module 'rc-form/es/FormScope' {
  declare module.exports: any;
}

declare module 'rc-form/es/index' {
  declare module.exports: any;
}

declare module 'rc-form/es/propTypes' {
  declare module.exports: any;
}

declare module 'rc-form/es/utils' {
  declare module.exports: any;
}

declare module 'rc-form/lib/createBaseForm' {
  declare module.exports: any;
}

declare module 'rc-form/lib/createDOMForm' {
  declare module.exports: any;
}

declare module 'rc-form/lib/createFieldsStore' {
  declare module.exports: any;
}

declare module 'rc-form/lib/createForm' {
  declare module.exports: any;
}

declare module 'rc-form/lib/createFormField' {
  declare module.exports: any;
}

declare module 'rc-form/lib/FormScope' {
  declare module.exports: any;
}

declare module 'rc-form/lib/index' {
  declare module.exports: any;
}

declare module 'rc-form/lib/propTypes' {
  declare module.exports: any;
}

declare module 'rc-form/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-form/dist/rc-form.js' {
  declare module.exports: $Exports<'rc-form/dist/rc-form'>;
}
declare module 'rc-form/dist/rc-form.min.js' {
  declare module.exports: $Exports<'rc-form/dist/rc-form.min'>;
}
declare module 'rc-form/es/createBaseForm.js' {
  declare module.exports: $Exports<'rc-form/es/createBaseForm'>;
}
declare module 'rc-form/es/createDOMForm.js' {
  declare module.exports: $Exports<'rc-form/es/createDOMForm'>;
}
declare module 'rc-form/es/createFieldsStore.js' {
  declare module.exports: $Exports<'rc-form/es/createFieldsStore'>;
}
declare module 'rc-form/es/createForm.js' {
  declare module.exports: $Exports<'rc-form/es/createForm'>;
}
declare module 'rc-form/es/createFormField.js' {
  declare module.exports: $Exports<'rc-form/es/createFormField'>;
}
declare module 'rc-form/es/FormScope.js' {
  declare module.exports: $Exports<'rc-form/es/FormScope'>;
}
declare module 'rc-form/es/index.js' {
  declare module.exports: $Exports<'rc-form/es/index'>;
}
declare module 'rc-form/es/propTypes.js' {
  declare module.exports: $Exports<'rc-form/es/propTypes'>;
}
declare module 'rc-form/es/utils.js' {
  declare module.exports: $Exports<'rc-form/es/utils'>;
}
declare module 'rc-form/lib/createBaseForm.js' {
  declare module.exports: $Exports<'rc-form/lib/createBaseForm'>;
}
declare module 'rc-form/lib/createDOMForm.js' {
  declare module.exports: $Exports<'rc-form/lib/createDOMForm'>;
}
declare module 'rc-form/lib/createFieldsStore.js' {
  declare module.exports: $Exports<'rc-form/lib/createFieldsStore'>;
}
declare module 'rc-form/lib/createForm.js' {
  declare module.exports: $Exports<'rc-form/lib/createForm'>;
}
declare module 'rc-form/lib/createFormField.js' {
  declare module.exports: $Exports<'rc-form/lib/createFormField'>;
}
declare module 'rc-form/lib/FormScope.js' {
  declare module.exports: $Exports<'rc-form/lib/FormScope'>;
}
declare module 'rc-form/lib/index.js' {
  declare module.exports: $Exports<'rc-form/lib/index'>;
}
declare module 'rc-form/lib/propTypes.js' {
  declare module.exports: $Exports<'rc-form/lib/propTypes'>;
}
declare module 'rc-form/lib/utils.js' {
  declare module.exports: $Exports<'rc-form/lib/utils'>;
}
