// flow-typed signature: c2c27c93c957368c5c693dc60b3ca89c
// flow-typed version: <<STUB>>/react-screen-size_v^2.0.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-screen-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-screen-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-screen-size/dist/react-screen-size' {
  declare module.exports: any;
}

declare module 'react-screen-size/dist/react-screen-size.min' {
  declare module.exports: any;
}

declare module 'react-screen-size/es/connectScreenSize' {
  declare module.exports: any;
}

declare module 'react-screen-size/es/index' {
  declare module.exports: any;
}

declare module 'react-screen-size/es/MediaProvider' {
  declare module.exports: any;
}

declare module 'react-screen-size/es/medias' {
  declare module.exports: any;
}

declare module 'react-screen-size/es/provider' {
  declare module.exports: any;
}

declare module 'react-screen-size/lib/connectScreenSize' {
  declare module.exports: any;
}

declare module 'react-screen-size/lib/index' {
  declare module.exports: any;
}

declare module 'react-screen-size/lib/MediaProvider' {
  declare module.exports: any;
}

declare module 'react-screen-size/lib/medias' {
  declare module.exports: any;
}

declare module 'react-screen-size/lib/provider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-screen-size/dist/react-screen-size.js' {
  declare module.exports: $Exports<'react-screen-size/dist/react-screen-size'>;
}
declare module 'react-screen-size/dist/react-screen-size.min.js' {
  declare module.exports: $Exports<'react-screen-size/dist/react-screen-size.min'>;
}
declare module 'react-screen-size/es/connectScreenSize.js' {
  declare module.exports: $Exports<'react-screen-size/es/connectScreenSize'>;
}
declare module 'react-screen-size/es/index.js' {
  declare module.exports: $Exports<'react-screen-size/es/index'>;
}
declare module 'react-screen-size/es/MediaProvider.js' {
  declare module.exports: $Exports<'react-screen-size/es/MediaProvider'>;
}
declare module 'react-screen-size/es/medias.js' {
  declare module.exports: $Exports<'react-screen-size/es/medias'>;
}
declare module 'react-screen-size/es/provider.js' {
  declare module.exports: $Exports<'react-screen-size/es/provider'>;
}
declare module 'react-screen-size/lib/connectScreenSize.js' {
  declare module.exports: $Exports<'react-screen-size/lib/connectScreenSize'>;
}
declare module 'react-screen-size/lib/index.js' {
  declare module.exports: $Exports<'react-screen-size/lib/index'>;
}
declare module 'react-screen-size/lib/MediaProvider.js' {
  declare module.exports: $Exports<'react-screen-size/lib/MediaProvider'>;
}
declare module 'react-screen-size/lib/medias.js' {
  declare module.exports: $Exports<'react-screen-size/lib/medias'>;
}
declare module 'react-screen-size/lib/provider.js' {
  declare module.exports: $Exports<'react-screen-size/lib/provider'>;
}
