// flow-typed signature: 789a1f842b8ef64a79f8eac890c6917f
// flow-typed version: <<STUB>>/react-snowstorm_v0.0.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-snowstorm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-snowstorm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-snowstorm/lib/index' {
  declare module.exports: any;
}

declare module 'react-snowstorm/lib/snowstorm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-snowstorm/lib/index.js' {
  declare module.exports: $Exports<'react-snowstorm/lib/index'>;
}
declare module 'react-snowstorm/lib/snowstorm.js' {
  declare module.exports: $Exports<'react-snowstorm/lib/snowstorm'>;
}
